### ISSUE TITLE
Help file missing

### ISSUE THREAD

**Issue by gnbl** [szieke/ScriptCommunicator_serial-terminal#12]
Help > Manual results in 

> error 
> could not open Manua_ScriptCommunicator.pdf

**Comment by szieke** [comment]
Hi,

which prebuild version do you use?

**Comment by gnbl** [comment]
Oh, sorry: https://sourceforge.net/projects/scriptcommunicator/files/Windows/ScriptCommunicatorSetup_04_21_windows.zip/ on W7 x64. I can have another look tomorrow.

**Comment by szieke** [comment]
Hi,

I have tested it on W7 x64 too. Can you rerun the installer (https://sourceforge.net/projects/scriptcommunicator/files/Windows/ScriptCommunicatorSetup_04_21_windows.zip/) and see if it works?

**Comment by gnbl** [comment]
Will try to try next week...

**Comment by gnbl** [comment]
Fresh download, same result. But maybe this helps to reproduce:
The installer should check if elevated priviliges (Administrator) are required, or it will fail if they are needed.
I suspect installing as admin is also the reason it does not find the PDF, which _does exist_ in the install dir (C:\Program Files (x86)\ScriptCommunicator). So a path might be off.

**Comment by szieke** [comment]
Hi,

thx for your time. 
I have copied my installation folder to C:\Program Files (x86)\ScriptCommunicator (with admin rights). Then I started ScriptCommunicator with and without admin priviliges. In both scenarios I get the same error message (could not open Manual_ScriptCommunicator.pdf).
I think that maybe the path is the problem (it contains spaces). I will check this.

Thx again for your time.

**Comment by szieke** [comment]
Hi,

the problem was that QDesktopServices::openUrl(QUrl(path)) with a path which contains spaces does not work. 
The solution is QDesktopServices::openUrl(QUrl::fromLocalFile(path)) .

Thx for reporting the bug and for your time
