### ISSUE TITLE
why not have int8_t byteArrayToInt8(Array<unsigned char> data, bool littleEndian)

### ISSUE THREAD

**Issue by jabezGit** [szieke/ScriptCommunicator_serial-terminal#14]
When i was writing a script for udp decod function ,i not find Conversion function for byteArrayToInt8 && byteArrayToUint8.
And i find can't use some javaScript's function ,like byteArray , dataView.

**Comment by szieke** [comment]
Hi,

for UInt8 you can use:
var unsignedVar= array[0] & 0xff;

for Int8 you can use conv.unsignedCharToSignedChar:
var signedVar = unsignedVar(array[0]);

**Comment by jabezGit** [comment]
thinks ,
1 , conv.unsignedCharToSignedChar : it work! 👍 
2 , yes, If you do not mind.
