### ISSUE TITLE
createProcessAsynchronous working directory 

### ISSUE THREAD

**Issue by hanusan** [szieke/ScriptCommunicator_serial-terminal#15]
if working directory of the process is set to another that ScriptCommunicator directory function not work properly. workaround is copy some dll library (libgcc,libstdc++,libwinpthread, Qt5Core) from ScriptCommunicator directory to working directory.

Windows 10
SC 05.02
qt 5.5.1

**Comment by szieke** [comment]
Hi,

you have started an external process with createProcessAsynchronous from script. Is this correct? And this process needs dlls which are not in his working directory?

**Comment by hanusan** [comment]
Hello,

Yes i want to run the process from the script using createProcessAsynchronous. 
The running application does not need external libraries, but I need to run it in some specific working directory.

I had a bug somewhere else in the code and so I tried example that is by the standard ScriptCommunicator installation - testProcess with change working directory. But I didn't realize that TestProcess.exe was not created as a static but needs some libraries.

function CreateProcessAsynchronous works flawlessly.

My mistake, sorry.
