### ISSUE TITLE
Sets the background color of a gui element QCheckBox

### ISSUE THREAD

**Issue by hanusan** [szieke/ScriptCommunicator_serial-terminal#16]
QCheckBox.setBackgroundColor( String color)

I think it does not work right, from my point of view it did not work.

**Comment by szieke** [comment]
Hi,

that's a problem in Qt. With some GUI elements (like QChechbox) this doesn't work (they ignore the palette color for the background).
I have search and tried several things for hours now. But I could not change the background color dynamically (if I set the Button role (in QtDesigner) to e.g. green and autoFillBackground to true then the background color is green (but I cannot change it dynamically form my code).

**Comment by hanusan** [comment]
Hello,

thank you for the explanation.
