### ISSUE TITLE
Codeeditor/Codecompletition ScriptToolButton.api

### ISSUE THREAD

**Issue by kohennigs** [szieke/ScriptCommunicator_serial-terminal#20]
Missing e.g. "setChecked" whyle working with ScriptToolButton.

maybe a copy n paste oops?

apitFiles\ScriptToolButton.api - line 23..27 ScriptButton -> ScriptToolButton

"So geht das nicht!" 

Greetz

**Comment by szieke** [comment]
Thx for reporting this issue. Already fixed this.
