### ISSUE TITLE
ASCII is wrong

### ISSUE THREAD

**Issue by taylor-an** [szieke/ScriptCommunicator_serial-terminal#21]
Hello,

I printed string via uart as below.

`printf("SM Mask	   : %d.%d.%d.%d\n\r",gWIZNETINFO.sn[0],gWIZNETINFO.sn[1],gWIZNETINFO.sn[2],gWIZNETINFO.sn[3]);`

But I got "SM Maskÿ".

![image](https://user-images.githubusercontent.com/44388468/56548140-3f30dc80-65ba-11e9-81f5-7d512a75a89f.png)

Is there something I missed?

Thank you.
BR.

**Comment by szieke** [comment]
Hi,

can you activate the hex console and take a screenshot too please (then I can see the exact data which ScriptCommunicator receives for this line)? Or maybe you can check what a character ScriptCommunicator receives after the 'k'.

PS: ScriptCommunictor should print a ÿ only for non ASCII characters.

Regards,
Stefan

**Comment by taylor-an** [comment]
Hello,

You're right.

I didn't notice that.

* ASCII Console 
`SM Maskÿ   : 255.255.255.0`

![image](https://user-images.githubusercontent.com/44388468/56573875-f9493800-65fc-11e9-9e32-30ee5b7c4cb2.png)

* HEX Console 
`53 4d 20 4d 61 73 6b 09 20 20 20 3a 20 32 35 35 2e 32 35 35 2e 32 35 35 2e 30 0a`

![image](https://user-images.githubusercontent.com/44388468/56573893-0108dc80-65fd-11e9-8975-4292b8d04021.png)

However, the other terminal printed as below.

Is it a bug that needs to be fixed? Or is it a feature?

![image](https://user-images.githubusercontent.com/44388468/56574480-4ed21480-65fe-11e9-84ee-d0df64cc54f1.png)

or

![image](https://user-images.githubusercontent.com/44388468/56574568-8d67cf00-65fe-11e9-9b3e-3e583e4b73df.png)

Thank you.
BR.

**Comment by szieke** [comment]
Hi,

this is not a bug. If ScriptCommunicator would print a space instead of a ÿ then you would not know that your data from the UART is not correct. 
The question is why is your UART sending a 0x09? Maybe this is a bug in your UART driver?

Regards,
Stefan
