### ISSUE TITLE
Create  an exe file

### ISSUE THREAD

**Issue by zonalimitatore** [szieke/ScriptCommunicator_serial-terminal#24]
Hello there!
I've create a program,and i wanna put .sce file,and .ui & .js (present in a subfolder named "scripts"),in a single file not editable one time compiled.
It's a pure dream,or i can do somethings?

Thanks for the great job

**Comment by szieke** [comment]
Hi,

you can find an example under winRarSfx that shows how to create a self extracting zip file (sfx) with winrar (this zip file contains the worker script and all needed Scriptcommunicator files).
If you start the created sfx file all included files are extracted into a temporary folder and the script is started. After Scriptcommunicator is stopped this temporary folder is deleted.

Regards,
Stefan

**Comment by zonalimitatore** [comment]
Thanks for response.
Right,I see that function,but in that way,I still need have script communicator installed?

**Comment by szieke** [comment]
No, all needed files are in the sfx file.
