### ISSUE TITLE
Console wrapping

### ISSUE THREAD

**Issue by bryceschober** [szieke/ScriptCommunicator_serial-terminal#25]
I have a really long-line-length output that I actually don't want to wrap before its included `\r\n`, and I can't figure out a way to keep it from wrapping in the ascii output pane.

In the "console options" page, of all of the "new line" configurations, I have only "new line at byte LF" enabled.

I'm running the 5.10 release on Ubuntu 14.04 x64.

**Comment by szieke** [comment]
Hi Bryce,

a line in a console is automatically wrapped at the right border of the console. You cannot prevent that. But I think I will add this in a future release.
