### ISSUE TITLE
Second Y axis support in plot widget

### ISSUE THREAD

**Issue by desowin** [szieke/ScriptCommunicator_serial-terminal#26]
Currently the plot widget is limited to single Y axis. The underlying QCustomPlot library supports dual Y axis (ScriptCommunicator just draws the ticks on second Y axis). It would be really useful if there was ability to write script that utilize two Y axes. Example use case is to be able to plot Temperature and Voltage (or Voltage and Current) on the same plot.

**Comment by szieke** [comment]
I will will add this in a future release. Thx for your suggestion.
