### ISSUE TITLE
Version 5.11 does not work on macOS 10.15.6 Catalina

### ISSUE THREAD

**Issue by THorst92** [szieke/ScriptCommunicator_serial-terminal#28]
Hello,

tried to start the program but following failure message appears.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/22470970/92728315-cd089580-f370-11ea-870a-bc5e657b3b17.png">

Operating system: macOS 10.15.6 Catalina

Best regards

**Comment by szieke** [comment]
Hi,
I compiled ScriptCommunicator on Yosemite 10.10 (virtual machine).  I will try to get a newer version of MacOS.

Thx for your bug report.
