### ISSUE TITLE
Scripts become unavailable after moving the folder to another directory

### ISSUE THREAD

**Issue by akiyamaakira** [szieke/ScriptCommunicator_serial-terminal#29]
### Version: 
ScriptCommunicator 05.12 Windows no installer

### Step:
0. delete all files in %userprofile%\Documents\ScriptCommunicator
1. unzip ScriptCommunicator_05_12_windows_no_installer.zip
2. double click ScriptCommunicator.exe in folder "ScriptCommunicator_05_12_windows_no_installer"
3. close ScriptCommunicator main window
4. move ScriptCommunicator_05_12_windows_no_installer folder to any other directory
5. double click ScriptCommunicator.exe again
6. double click any script in the right Scripts list

### Result:
shows up a window and says: error starting script.....

**Comment by szieke** [comment]
If you start ScriptCommunicator and the folder %userprofile%\Documents\ScriptCommunicator does not exist then ScriptCommunicator copies a default settings file. ScriptCommunicator sets the paths of the example scripts in the settings file to the current ScriptCommunicator directory.
If you move the ScriptCommunicator folder the paths of the example script are wrong. 
You have to remove the scripts in the script window and add the example script that you want to execute.
