### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by zhangchunlin** [szieke/ScriptCommunicator_serial-terminal#33]
I try to find but I could not find any information in your software and source code that if I want to use this tool in work, should I buy a commercial license or I can use it feely, I sent email but no repsonse, could you answer the question?
Thank you!

**Comment by szieke** [comment]
I published ScriptCommunicator under GPL3. This means you can use the program for free. But if you modify the source code you have to publish your changes/new functionalities.

**Comment by zhangchunlin** [comment]
Thank you for the clarification!
