### ISSUE TITLE
WebViewLibs not found (v 5.14 through 5.16)

### ISSUE THREAD

**Issue by mmrein** [szieke/ScriptCommunicator_serial-terminal#35]
Hello, I've tried running the xterm example, but I get "Missing libraries" error. 

Obviously, I downloaded the WebViewLibs and tried to copy the files to various locations (install folder, subfolder, config folder, script folder..) but with no luck. I had some older SC versions on my system and it turns out that **it does work as expected in v5.12 and 5.13** (copy WebView library files to install folder), but not in v5.14 or 5.16.

This was tested on Win10 64bit, but initially tried on Ubuntu 20.04 too (v5.16 with no luck).

**Comment by szieke** [comment]
Hi,

I switched to Qt 5.14. In this version QWebView is not available any more. I forgot to remove the example.
