### ISSUE TITLE
Minor Bug: Console updates incorrectly after settings change (data loss)

### ISSUE THREAD

**Issue by flo80** [szieke/ScriptCommunicator_serial-terminal#37]
# Issue 
console data loss when using break after x bytes and triggering refresh of console (open/close settings)

# Reproduction

Steps:
- set console settings to only break after e.g. 7* bytes  but not after LF/CR
- get some data (formatted correctly)
- open and close settings again

Expected outcome: console output should not change

Outcome: console output gets reformatted and some data is lost 
- input data gets truncated (see examples)
- sent data is lost 

Tested with:
- Windows 10,
- Version 05.18
- serial and TCP connections
- settings other than break after x bytes seem to have no impact (also e.g happens in mixed mode)

*) all values for x work except for 1 - then the behaviour is as expected

# Example

## Hex

Output before changing settings: 
```
31 32 33 34 35 36 37
37 36 35 34 33 32 0a
```

Output after changing settings:
```
34 35 36 37
34 33 32 0a
```

## UTF8

Output before changing settings: 
```
ABCDEFG
HIJKLMN
OPQRSTU
VWXYZ
```

Output after changing settings:
```
DEFG
KLMN
RSTU
ZY
```

# Potential solution

I only looked at the code but could not debug it (don't have a QT toolchain). But likely not all data data is stored in `m_storedConsoleData`. 

For input data, it seems like it the first 3 bytes after a line break are missing. Looking at the code I don't really have an explanation since the same data should get printed initially and stored 😞

**Comment by szieke** [comment]
I will have a look into it next week. Thx for reporting the bug.

**Comment by szieke** [comment]
I tried to reproduce your described behavior it on my Windows 11 PC but it worked correctly. 
But I removed the reinserting of the data into the console if the Settings Window is closed (is unnecessary). Therefore you shouldn't have this behavior in the next release of ScriptCommunicator on your PC.
