### ISSUE TITLE
ESP32 Backtrace Decoder

### ISSUE THREAD

**Issue by mmrein** [szieke/ScriptCommunicator_serial-terminal#39]
Hi Stefan, 
I'm currently working on script based on ANSIColorConsole which adds an option to automatically decode backtrace in ESP32 log outputs. 

I see by the current activity that there may be new release comming and I believe it would be nice to include it if that is the case. It should be ready in next few days. 

What is the current status, would you mind waiting for it?

**Comment by szieke** [comment]
Hi,

I'm porting ScriptCommunicator to Qt6.4.2 at the moment. For this I had to change a lot (e.g. new script engine). Currently I'm testing all functionalities and fixing bugs. To complete all my tests I have to get specific HW (e.g PCAN Adapter) which is at my work place. I wont't be able to get this HW untill next week. In other words I will release ScriptCommunicator next week.

By the way, I changed the ANSIColorConsole  script (I changed the color strings in line 7 to 15).

**Comment by mmrein** [comment]
> In other words I will release ScriptCommunicator next week.

Ok, sounds good!

> If you want I can upload a prerelease for your platform, then you can check if your script can be executed with the new script engine).

Yea, that would be ideal. I'm using both Ubuntu and Windows quite regularly and I try to keep the compatibility, so I could even test both.

----

> By the way, I changed the ANSIColorConsole script (I changed the color strings in line 7 to 15 and I changed \033 to \u001b (the new script engine throwed an exception)).

The `\u001b` should be no problem, but there could be an issue with the color definition because specifically the ESP log sends additional `0;` before the actual color number and frankly, ANSI sequences can be sent with mupltiple commands after the `[` at once. 

**Options:**
- Right now I would simply keep the ANSI console with basic definition as you did (as it should be more general) and use the custom definiton with additional `0;` in ESP console only (as it is targeted for that).
- Ideally we should use regex that takes possible multiple command into perspective, but I'm not very familiar with those.

--

And more thanks to you for this great toolset :-)

**Comment by szieke** [comment]
I uploaded a prerelease for Windows here: https://sourceforge.net/projects/scriptcommunicator/files/Test/
I have no time to create the prerelease for Linux today. But I will upload it tomorrow and write you a message here.

**Comment by mmrein** [comment]
Btw, ESPConsole script will store its small settings file. Placing it right next to script file should be ok on linux, but may be problem for windows as it may be in Program Files by default. 

Do you think it is good idea to just use `getUserDocumentsFolder()` and store it right there? Or is there a better way to get something like ScriptCommunicator settings folder?

**Comment by szieke** [comment]
I think it would be the best if you create your own folder in getUserDocumentsFolder().

`var folder = scriptThread.getUserDocumentsFolder() + "/ANSIColorConsole";
if(!scriptFile.checkDirectoryExists(folder, false))
{
	if(!scriptFile.createDirectory(folder))
	{
		//Error
	}
}`

I uploaded the prerelease for Linux.

**Comment by mmrein** [comment]
Ok, some basic testing of the new script, both on Windows and Ubuntu without major issues so far. I will keep using it for now and eventually do some more testing with older scripts too.

Small issue on linux with Designer - there are some icons missing in file menu, see:

![obrazek](https://user-images.githubusercontent.com/55082189/224944363-d16c6aa3-15ba-4675-ae69-49fc41eb7e21.png)

Other issue on linux is that scripts don't work with space in path, but that has been present in v5 too. I can live with that.

![obrazek](https://user-images.githubusercontent.com/55082189/224945779-ad4fbd58-89ef-4284-9540-e705ff264927.png)

For the settings file, I see what you mean. I will try to go even further and do something like %LOCALAPPDATA%/SCScripts on windows and ~/.config/SCScripts on linux if possible. Should be easy on linux, but may be problem with environment variables on windows.

**Comment by szieke** [comment]
I will look into it

**Comment by szieke** [comment]
1. Scope of const
I have tried several things but in the current Qt version const variables are only valid insside the corresponsing script. If you want to include your const.js in other files you have to replace const with var.

**Comment by szieke** [comment]
I had an idea, I think I can parse the included script myself and add the const variables to the script engine (I have the code in the editor already). But I'm not sure if I have time to add this for the current release.

**Comment by mmrein** [comment]
**1-3:** Got it, soungs good to me. It would be interesting to try, timeframe is not an issue with that as I can keep old scripts with older version for now. But it would be nice for backwards compatibility.

And regarding the config file locations, I usually don't prefer to create anything directly in user documents folder, whether it is file or folder. While it works pretty well for ScriptCommunicator itself, for things like my script I would rather prefer proper config location as user shouldn't need to access it directly anyways.

I dug a bit and found https://doc.qt.io/qt-6/qstandardpaths.html#StandardLocation-enum, from which the `HomeLocation`,  `ConfigLocation` and especially  `GenericConfigLocation` is what I hoped for. So I installed QT5 (as it is part of Ubuntu 20 repo and works out of the box even without registration) and compiled SC 05.20 with following added to *scriptThread.h*:

```c++
    ///Returns the user home folder.
    /// MAC:"~"; WIN:"C:/Users/<USER>"; LINUX:"~"
    Q_INVOKABLE QString getUserHomeFolder(void){return QStandardPaths::writableLocation(QStandardPaths::HomeLocation);}

    ///Returns a directory location where user-specific configuration files should be written. This may be either a generic value or application-specific.
    /// MAC: "~/Library/Preferences"; WIN:"C:/Users/<USER>/AppData/Local/<APPNAME>","C:/ProgramData/<APPNAME>"; LINUX:"~/.config","/etc/xdg"
    Q_INVOKABLE QString getUserConfigFolder(void){return QStandardPaths::writableLocation(QStandardPaths::ConfigLocation);}

    ///Returns a directory location where user-specific configuration files shared between multiple applications should be written
    /// MAC: "~/Library/Preferences"; WIN:"C:/Users/<USER>/AppData/Local","C:/ProgramData"; LINUX:"~/.config","/etc/xdg"
    Q_INVOKABLE QString getUserGenericConfigFolder(void){return QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);}
```

Surprisingly enought it worked, although script editor obviously did not know those as I only copied the generated SC executable to existing SC package. **Would you consider adding those eventually?**

**Comment by szieke** [comment]
I will upload a prerelease that will contain these new functions tomorrow.

**Comment by mmrein** [comment]
> I will upload a prerelease that will contain these new functions tomorrow.

That would be amazing! I'll wait for that so I can use and test it in the ESPConsole, the I'll PR it. Thanks!

**Comment by mmrein** [comment]
OK, PR https://github.com/szieke/ScriptCommunicator_serial-terminal/pull/40 is up and I saw the new functions too, so it should be good to go.

**Comment by szieke** [comment]
I uploaded the new prerelease.

**Comment by mmrein** [comment]
Nice, will try and let you know.

**Comment by mmrein** [comment]
Ok, minor change in default label colors (https://github.com/szieke/ScriptCommunicator_serial-terminal/pull/41)  in my script and there is possible logical issue, but that should not affect correct execution, only slightly the "user experience" if incorrect files are selected. I can't promise I'll fix it untill current release, probably leave it for next one.

Regarding ScriptCommunicator itself, everything seems ok to me (aside from that minor issue with missing icons in Designer on Ubuntu 20).

**Comment by szieke** [comment]
I merged your changes and fixed the two issues on Ubuntu.
