### ISSUE TITLE
scriptFile.checkFileExists issue

### ISSUE THREAD

**Issue by GDM-VA** [szieke/ScriptCommunicator_serial-terminal#44]
Hi Stefan,
it seems **scriptFile.checkFileExists** doesn't work properly on my side.
I'm using ScriptCommunicator 6.00 and Windows 10.
My worker script is stored on a different folder respect to the file I'm trying to check.
The following code always returns false, even if folder & file are present:
```
var fileExist = scriptFile.checkFileExists("C:/Data/MyData.bin");
if (fileExist == true)
{
	printString ("File " + filename + " exists");
}
else
{
	printString ("Error! File " + filename + " doesn't exists");
}

```
The code returns this message:
`Error! File C:/Data/MyData.bin doesn't exists
`
The only way I found to fix the problem is to store my file on the script folder and remove the path from the checkFileExist input parameter.
Thank you in advance for your support.
KR

**Comment by mmrein** [comment]
Hi, the checkFileExists() defaults to relative path if parameter is not provided. All you need to do is:

    var fileExist = scriptFile.checkFileExists("C:/Data/MyData.bin", false);

**Comment by mmrein** [comment]
Its Martin, not Stefan, but you are welcome anyway :)

**Comment by GDM-VA** [comment]
Sorry Martin :-)
Thank you for your support.
