### ISSUE TITLE
Serial port Parity is useless

### ISSUE THREAD

**Issue by YxxP** [szieke/ScriptCommunicator_serial-terminal#47]
Hi 
what ever it changed with the PARITY setting in the setting interface，I can receive with the correct data（Using another Serial port simulator with different PARITY）。
Append:I connect the port using the “virtual serial port(Eltima Software)”。

**Comment by szieke** [comment]
Hi,

the reason for this is that you use virtual serial ports (the data is transferred only inside your PC and therefore the parity is ignored). If you use a 'real' serial port then your partity must match the parity of your communiction device.
