### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by profdc9** [szieke/ScriptCommunicator_serial-terminal#48]
Could you have a couple of options so that:

1.  In the text field where one can type characters to be directly sent over the connection, a CR, LF, or CR/LF is automatically sent at the end of the line even if no end of line character is included, and perhaps the sending happens when the carriage return is pressed?
2.  Could there be an option to automatically erase the text field after the characters have been sent?

Thanks for your consideration.  I need these features to help support communication with a serial device I am making, and this would avoid certain mistakes from being made.

**Comment by szieke** [comment]
1. ScriptCommunicator has the option 'send on enter key'. If your format is utf8 and you press enter at the end of you data then this will be send (CR, LF or CR+LF). Another possibility is to add a sequence sqript that adds it (see attachment).
If you don't want to press the send button you can also press Alt+Enter.

2. What is the reason for this (maybe I have a solution without modifying ScriptCommunicator)?

**Comment by profdc9** [comment]
The reason I was asking for these changes is that it would be helpful to
have the ScriptCommunicator be an easy out-ot-the-box alternative to
Arduino's IDE serial monitor, which I am guessing many people use
ScriptCommunicator for because it shares many of the same features.  If you
look at the below picture, you can see that there is a blank for the
message, a drop-down box for the end-of-line character, and the baud rate.
The baud rate is seldom required to be changed for a particular device, and
it is occasionally helpful to switch on and off the newline character.

Pressing Alt-enter works of course but when one is trying to react quickly
or use this very frequently, it comes frustratingly error-prone to hit
Enter instead of Alt-Enter.  Arduino's IDE also can clear the input message
text field and scroll it back which is helpful for debugging interactive
input programs.  It would be really helpful when suggesting
ScriptCommunicator as a means of helping debug or use serial devices like
Arduino's IDE, or using these devices, if there were features so that it
could behave "out-of-the-box" like Arduino's IDE without having to install
the entirety of Arduino's IDE which is a pretty heavyweight solution if all
one needs is a simple split-terminal like Arduino offers.  There are no
other real options I have found and ScriptCommander's functionality is the
closest offered in a cross-platform program.

Thank you,

Dan

[image: image.png]

**Comment by szieke** [comment]
Hi,

I have uploaded a prerelease here: 
https://sourceforge.net/projects/scriptcommunicator/upload/Test/

Please have a look at it and write me what you think.

**Comment by profdc9** [comment]
Sorry, I did not see the link in the project that made the test version
available.

I have tried it and it is exactly what I wanted!  Thank you!

Best,
Dan
