### ISSUE TITLE
libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by mmrein** [szieke/ScriptCommunicator_serial-terminal#49]
Hi Stefan, V06.02 or V06.03 does not want to run under Ubuntu 20.04, `ScriptCommunicator.sh` returns error:

```bash
./ScriptCommunicator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ScriptCommunicator)
```

Seems like an issue with newer GCC compiler. V06.01 or earlier runs without issues.

**Comment by mmrein** [comment]
That would be it, Ubuntu 20.04 uses GCC 9 by default (9.4.0 on Ubuntu 20.04.6) and can only be updated to GCC 10. 

But it should be possible to switch to older version using `update-alternatives` (as described here for example: https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-22-04-lts-jammy-jellyfish). What do you think?

**Comment by szieke** [comment]
I think I setup a virtual machine with Ubuntu 20.4 and compile it.

**Comment by szieke** [comment]
I uploaded a new version for Linux (6.3.1) that should run under Ubuntu 20.4. Can you try this version and give me response please?

**Comment by mmrein** [comment]
@szieke Unfortunatelly still the same error.
