### ISSUE TITLE
missing "scriptPlotwidget.h"

### ISSUE THREAD

**Issue by andreatta** [szieke/ScriptCommunicator_serial-terminal#8]
Cannot compile due to missing header file.

scriptClasses/plotwindow.h:30:30: fatal error: scriptPlotwidget.h: No such file or directory
 #include "scriptPlotwidget.h"

**Comment by szieke** [comment]
I hate SourceTree/Window (I renamed them from scriptplotwidget to 
scriptPlotwidget). Now the trunk should compile.

Best regards,
Stefan

Am 18.07.2016 um 10:00 schrieb cee:
